# ─── DB + Redis passwords (generated by Terraform) ───────────────────────────

resource "aws_secretsmanager_secret" "db_password" {
  name                    = "medavida/${var.environment}/db-password"
  recovery_window_in_days = var.environment == "production" ? 30 : 0
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db.result
}

resource "aws_secretsmanager_secret" "redis_password" {
  name                    = "medavida/${var.environment}/redis-password"
  recovery_window_in_days = var.environment == "production" ? 30 : 0
}

resource "aws_secretsmanager_secret_version" "redis_password" {
  secret_id     = aws_secretsmanager_secret.redis_password.id
  secret_string = random_password.redis.result
}

# ─── Bot secrets (populated manually after deploy) ───────────────────────────
# These are injected as environment variables into the ECS task and passed
# to Medplum bots via Bot.secret[] in the Medplum admin UI.

resource "aws_secretsmanager_secret" "stripe_secret_key" {
  name                    = "medavida/${var.environment}/stripe-secret-key"
  recovery_window_in_days = var.environment == "production" ? 30 : 0
}

resource "aws_secretsmanager_secret" "pharmacy_adapter_api_key" {
  name                    = "medavida/${var.environment}/pharmacy-adapter-api-key"
  recovery_window_in_days = var.environment == "production" ? 30 : 0
}
